### PR TITLE
fix #7 dub run har

### LINKED ISSUE #7: dub run har => Error: module `har` is in file 'archive/har.d' which cannot be read
`dub run` allows one to run a package without having to git clone it somewhere or any other setup, eg:

```
dub run digger -- build "master +dmd#7988"
dub run dfmt -- --inplace foo.d
```

however:
```
dub run har
Error: module `har` is in file 'archive/har.d' which cannot be read
```
(unless it's run from a git clone of har, which is not the point)

### PR DESCRIPTION
**Pull request by timotheecour**
not sure how to test this locally so i don't know if it will fix the bug for sure

### CODE REVIEW

**Comment by marler8997** [comment]
if this is the fix then this is surely a bug in DUB.  It should work whether you specify the sourcePath or a set of sourceFiles.

**Comment by timotheecour** [comment]
I pushed a different fix and tested locally with dub add-local, it works

**Comment by marler8997** [comment]
does `dub build har:library` work and produce the library file?

**Comment by timotheecour** [comment]
yes

**Comment by marler8997** [comment]
I normally don't like the proliferation of nested directories, but I approve of this one because it allows you to use `-I<har-repo>/src` as an import path without exposing other files in the har repo.

**Comment by marler8997** [comment]
Add an empty `sourcePaths` to all the other packages as well

**Pull request merged**
